# roles tomcat-app/tasks/main.yml
---

- include_tasks: check-deploy-needed.yml

- include_tasks: deploy.yml
  when: tomcat_app_needs_deploy

- name: Make sure tomcat is started
  meta: flush_handlers

- include_tasks: tests.yml
- include_tasks: configure.yml
